version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - .postgres-data:/var/lib/postgresql/data
    networks:
      - internal
      - default

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
    networks:
      - internal 

  backend:
    container_name: backend
    build: ./backend
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    networks:
      - external  
      - internal
      - default

  frontend:
    container_name: frontend
    build: './frontend'
    ports:
      - 80:3000
    tty: true
    depends_on:
      - backend
    networks:
      - external     

networks:
  external:
    driver: bridge
  internal:
    driver: bridge
